### ISSUE TITLE
Up to date monitor / TV suggestions

### ISSUE THREAD

**Issue by vade** [OpenframeProject/Openframe-Docs#16]
It might make sense to have some suggestions for clean, minimal branding monitors that can be mounted with the PI in such a way to hide all but the power coord.

Obviously thin bezel displays, no large logo's, buttons on side or behind the display are important.

I'm happy to share once I arrive at some good options but it might be nice to have a wiki or a 'hardware' guide.

**Comment by jmwohl** [comment]
Yeah! This has come up a few times, and is definitely something we'd like to have. There's a bit of info [in the google group](https://groups.google.com/forum/#!topic/openframeio/lcAsKnyaMeY), but as you suggest it would be great to have a more complete hardware guide...

**Comment by jvolker** [comment]
It took a while, but I've created a [warning on TFT/e-paper displays in the docs](https://docs.openframe.io/#2-setup-a-frame).

I'm going to add a section on displays soon. I was thinking of writing a brief general guide recommending a type of panel, thin bezel, HDMI, etc. and maybe point to three specific examples (low, mid and high end) and maybe point back to the [Hardware category of the new forum](https://openframe.discourse.group/c/hardware/9). Please let me know if you have more thoughts on what this guide should include.

**Comment by jvolker** [comment]
I've added a brief guide mentioning a couple of topics: https://docs.openframe.io/#monitors

No specific models yet though.
