### ISSUE TITLE
Guide on adding artwork

### ISSUE THREAD

**Issue by jvolker** [OpenframeProject/Openframe-Docs#6]
I've written the following incomplete guide to give advice to people first using Openframe. It includes information on how to add artwork to the web app and some recommendations on what artwork format to pick. It also sums up issues I've faced with those extensions. 

https://paper.dropbox.com/doc/Guide-on-adding-artwork-to-Openframe--AoxD~g8WJ8GnA0UvG1e1bS8KAQ-2PIvl5ubOmCCH8t9yzkk8

I hope it's helpful to some people. Would be great to see some or all of the information integrated into this official Openframe documentation.
Feel free to improve and extend it!

**Comment by jmwohl** [comment]
Fantastic! Thanks for writing this up. Yes, we should try to incorporate this into the docs!

**Comment by jvolker** [comment]
Done. https://github.com/OpenframeProject/Openframe-Docs/commit/49df4bc2e143bef14a94f35e6298827f7028e918
